defaults: &defaults
  docker:
    - image: docker

version: 2
jobs:
  test:
    docker:
      - image: node:8.12.0
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install -g yarn
      - run: yarn install
      - run: yarn lint
      - run: yarn test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  build:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Login Docker hub
          command: echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin

      - run: docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 .

      - run:
          name: Publish image
          command: |
            docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
            docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
            docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH

workflows:
  version: 2
  web:
    jobs:
      - test

      - build:
          requires:
            - test
