---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "0/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: tutum/curl
            args:
            - /bin/sh
            - -c
            - 'curl -X POST --data "$(date)" http://hello-world-app/api/thing'
          restartPolicy: OnFailure