---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "0/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: hellocurl
        spec:
          containers:
            - name: hello
              image: curlimages/curl
              command:
                - /bin/sh
              args:
                - -c
                - 'curl -X POST -H "content-type: text/plain" --data "$(date)" http://hello-world-app/api/thing'
          restartPolicy: OnFailure
