apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: mysecret
    files:
      - my-secret

resources:
  - deployment-with-secret.yml
  - service.yml
  - ingress.yml
  - cronjob.yml

labels:
  - pairs:
      app: hello-world-app
